# Generated by Django 5.1.2 on 2024-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('link_url1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url2', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('list1', models.CharField(blank=True, max_length=255, null=True)),
                ('list2', models.CharField(blank=True, max_length=255, null=True)),
                ('list3', models.CharField(blank=True, max_length=255, null=True)),
                ('list4', models.CharField(blank=True, max_length=255, null=True)),
                ('list5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'About Text1',
                'verbose_name_plural': 'About Text1',
            },
        ),
        migrations.CreateModel(
            name='AboutText1list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'About Text1 List',
                'verbose_name_plural': 'About Text1 List',
            },
        ),
        migrations.CreateModel(
            name='AboutText2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('link_url1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url2', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('blockquote', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'About Text2',
                'verbose_name_plural': 'About Text2',
            },
        ),
        migrations.CreateModel(
            name='AboutTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'About Titles',
                'verbose_name_plural': 'About Titles',
            },
        ),
        migrations.CreateModel(
            name='Blogroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=255)),
                ('link_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Blogroll',
                'verbose_name_plural': 'Blogroll',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=255)),
                ('link_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoriesMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categories Main',
                'verbose_name_plural': 'Categories Main',
            },
        ),
        migrations.CreateModel(
            name='ContactSosials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link_url', models.URLField(max_length=255)),
                ('link_name', models.CharField(max_length=255)),
                ('class_link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Socials',
                'verbose_name_plural': 'Contact Socials',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image_class', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio.url')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='ResentBlogMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Resent Blog Main',
                'verbose_name_plural': 'Resent Blog Main',
            },
        ),
        migrations.CreateModel(
            name='ResentComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url2', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Resent Comments',
                'verbose_name_plural': 'Resent Comments',
            },
        ),
        migrations.CreateModel(
            name='ResentPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(max_length=255)),
                ('link_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Resent Posts',
                'verbose_name_plural': 'Resent Posts',
            },
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories.url')),
            ],
            options={
                'verbose_name': 'Stories',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('link_url', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='TreeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.CharField(blank=True, max_length=255, null=True)),
                ('description2', models.CharField(blank=True, max_length=255, null=True)),
                ('description3', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url', models.URLField(max_length=255)),
                ('link_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tree Template',
                'verbose_name_plural': 'Tree Template',
            },
        ),
        migrations.CreateModel(
            name='WebDesine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.CharField(max_length=255)),
                ('link_url1', models.URLField(blank=True, max_length=255, null=True)),
                ('link_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url2', models.URLField(blank=True, max_length=255, null=True)),
                ('link_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('list1', models.CharField(blank=True, max_length=255, null=True)),
                ('list2', models.CharField(blank=True, max_length=255, null=True)),
                ('list3', models.CharField(blank=True, max_length=255, null=True)),
                ('list4', models.CharField(blank=True, max_length=255, null=True)),
                ('list5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Web Desine',
                'verbose_name_plural': 'Web Desine',
            },
        ),
    ]
