# Generated by Django 5.1.2 on 2024-10-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_abouttext1_abouttext1list_abouttext2_abouttitles_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='TreeTemplate',
            new_name='FreeTemplate',
        ),
    ]
