# Generated by Django 5.1.2 on 2024-10-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_categorie_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freetemplate',
            options={'verbose_name': 'Free Template', 'verbose_name_plural': 'Free Template'},
        ),
        migrations.RenameField(
            model_name='webdesine',
            old_name='description1',
            new_name='description',
        ),
    ]
