# Generated by Django 4.2.13 on 2024-10-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_freetemplate_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactSosials',
            new_name='ContactSocials',
        ),
    ]
