# Generated by Django 4.2.13 on 2024-10-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_contactsosials_contactsocials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouttext1',
            name='description',
        ),
        migrations.AddField(
            model_name='abouttext1',
            name='description1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='abouttext1',
            name='description2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='abouttext1',
            name='description3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
