# Generated by Django 5.1.2 on 2024-10-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_photography_image_alter_portfolio_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_post')),
                ('description1', models.CharField(blank=True, max_length=1000, null=True)),
                ('description2', models.CharField(blank=True, max_length=1000, null=True)),
                ('description3', models.CharField(blank=True, max_length=1000, null=True)),
                ('description4', models.CharField(blank=True, max_length=1000, null=True)),
                ('description5', models.CharField(blank=True, max_length=1000, null=True)),
                ('description6', models.CharField(blank=True, max_length=1000, null=True)),
                ('description7', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_url1', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url2', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url3', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name3', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url4', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name4', models.CharField(blank=True, max_length=255, null=True)),
                ('link_url5', models.CharField(blank=True, max_length=255, null=True)),
                ('link_name5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Post',
            },
        ),
        migrations.CreateModel(
            name='BlogPostMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Blog Post Main',
                'verbose_name_plural': 'Blog Post Main',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=255)),
                ('image_title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='comments')),
            ],
            options={
                'verbose_name': 'Comments',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CommentsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Comments Main',
                'verbose_name_plural': 'Comments Main',
            },
        ),
    ]
