from django.contrib import admin

from .models import (
    HeaderText,
    FooterText,
    FreeTemplate,
    WebDesine,
    Portfolio,
    Stories,
    ResentBlogMain,
    ResentComments,
    ResentPosts,
    ResentComments,
    Blogroll,
    ContactSocials,
    AboutTitles,
    AboutText1,
    AboutText1list,
    AboutText2,
    CategoriesMain,
    Categories,
    Testimonial,
    BlogMain,
    Blog1,
    Blogs,
    Paging,
    PortfolioMain,
    WebImage,
    Photography,
    PrintMedia,
    BlogPostMain,
    BlogPost,
    CommentsMain,
    Comments
    )

admin.site.register(HeaderText)
admin.site.register(FooterText)
admin.site.register(FreeTemplate)
admin.site.register(WebDesine)
admin.site.register(Portfolio)
admin.site.register(Stories)
admin.site.register(ResentBlogMain)
admin.site.register(ResentComments)
admin.site.register(ResentPosts)
admin.site.register(Blogroll)
admin.site.register(ContactSocials)
admin.site.register(AboutTitles)
admin.site.register(AboutText1)
admin.site.register(AboutText1list)
admin.site.register(AboutText2)
admin.site.register(CategoriesMain)
admin.site.register(Categories)
admin.site.register(Testimonial)
admin.site.register(BlogMain)
admin.site.register(Blog1)
admin.site.register(Blogs)
admin.site.register(Paging)
admin.site.register(PortfolioMain)
admin.site.register(WebImage)
admin.site.register(Photography)
admin.site.register(PrintMedia)
admin.site.register(BlogPostMain)
admin.site.register(BlogPost)
admin.site.register(CommentsMain)
admin.site.register(Comments)
